# -*- coding: utf-8 -*-
"""Operations_Automation_cli.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T6i1CNl51nkbJ5DaOTUkRK2nwSkf7jl3
"""

# ==============================
# CLI Interface for Operations Automation
# ==============================

import argparse
from operations import automate_tasks, load_tasks, save_tasks

def main():
    parser = argparse.ArgumentParser(description="Operations Automation CLI")

    # Add new tasks
    parser.add_argument(
        "--add", "-a",
        nargs="+",
        help="Add new tasks. Example: --add 'Submit report' 'Send email'"
    )

    # Run automation
    parser.add_argument(
        "--run", "-r",
        action="store_true",
        help="Run all tasks with reminders and logging"
    )

    # Delay between tasks
    parser.add_argument(
        "--delay", "-d",
        type=int,
        default=2,
        help="Delay between tasks in seconds (default=2)"
    )

    args = parser.parse_args()

    # Load existing tasks
    tasks = load_tasks()

    # Add new tasks
    if args.add:
        tasks.extend(args.add)
        save_tasks(tasks)
        print(f"{len(args.add)} task(s) added successfully!")

    # Run automation
    if args.run:
        automate_tasks(tasks, args.delay)

if __name__ == "__main__":
    main()